### ISSUE TITLE
Can't enter auth code

### ISSUE THREAD

**Issue by KruyKaze** [Glitch-is/gpmdp-cli#4]
I read in the documentation "This code must be entered into gpmdp-cli when prompted to authorize the client to control GPMDP" but gpmdp-cli does not ask for the code that pops up in gmpdp.
I'm sure I'm missing something please help.

Thank you

**Comment by Glitch-is** [comment]
Are you getting any errors?

When you first run gpmdp-cli you should see something like the following

```
$> ./gpmdp-cli.py playback playPause
A UI will popup in GPMDP containing a 4 digit code
Enter code here:
```

Please tell me if you're getting different results

**Comment by KruyKaze** [comment]
Here's what I get:

./gpmdp-cli.py playback playPause
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/websockets/protocol.py", line 530, in transfer_data
    msg = yield from self.read_message()
  File "/usr/lib/python3.6/site-packages/websockets/protocol.py", line 582, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/usr/lib/python3.6/site-packages/websockets/protocol.py", line 647, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/usr/lib/python3.6/site-packages/websockets/protocol.py", line 712, in read_frame
    extensions=self.extensions,
  File "/usr/lib/python3.6/site-packages/websockets/framing.py", line 123, in read
    .format(length, max_size))
websockets.exceptions.PayloadTooBig: Payload length exceeds size limit (3772104 > 1048576 bytes)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./gpmdp-cli.py", line 123, in <module>
    asyncio.get_event_loop().run_until_complete(main(args))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "./gpmdp-cli.py", line 100, in main
    await connect(websocket, tokenFile)
  File "./gpmdp-cli.py", line 81, in connect
    authCode = await getAuthCode(websocket, tokenFile, payload)
  File "./gpmdp-cli.py", line 48, in getAuthCode
    code = await collectAuthCode(websocket, tokenFile, payload)
  File "./gpmdp-cli.py", line 55, in collectAuthCode
    await recvUntil(websocket, "connect")
  File "./gpmdp-cli.py", line 38, in recvUntil
    response = json.loads(await websocket.recv())
  File "/usr/lib/python3.6/site-packages/websockets/protocol.py", line 352, in recv
    yield from self.ensure_open()
  File "/usr/lib/python3.6/site-packages/websockets/protocol.py", line 514, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason


Thanks for the reply.

**Comment by Glitch-is** [comment]
I'm unable to recreate the error. What version of `WebSocket` are you running? I've tried versions `5.0` and `5.0.1`.

If that's not it then you can also tell me the `asyncio` version. I've tested version `3.4.3`.

**Comment by KruyKaze** [comment]
I'm running websockets-5.0.1 and asyncio-3.4.3

Thank you

**Comment by ConnorGriffin** [comment]
Getting the same error here.

Python 3.6.6
websockets: 5.0.1
asyncio: 3.4.3

```
$ ./gpmdp-cli.py playback playPause
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/websockets/protocol.py", line 530, in transfer_data
    msg = yield from self.read_message()
  File "/usr/lib/python3.6/site-packages/websockets/protocol.py", line 582, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/usr/lib/python3.6/site-packages/websockets/protocol.py", line 647, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/usr/lib/python3.6/site-packages/websockets/protocol.py", line 712, in read_frame
    extensions=self.extensions,
  File "/usr/lib/python3.6/site-packages/websockets/framing.py", line 137, in read
    frame = extension.decode(frame, max_size=max_size)
  File "/usr/lib/python3.6/site-packages/websockets/extensions/permessage_deflate.py", line 509, in decode
    .format(max_size))
websockets.exceptions.PayloadTooBig: Uncompressed payload length exceeds size limit (? > 1048576 bytes)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./gpmdp-cli.py", line 123, in <module>
    asyncio.get_event_loop().run_until_complete(main(args))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "./gpmdp-cli.py", line 101, in main
    await sendCommand(websocket, parseCommands(args))
  File "./gpmdp-cli.py", line 22, in sendCommand
    response = await asyncio.wait_for(recvCommand(websocket, requestID), TIMEOUT)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "./gpmdp-cli.py", line 31, in recvCommand
    response = json.loads(await websocket.recv())
  File "/usr/lib/python3.6/site-packages/websockets/protocol.py", line 352, in recv
    yield from self.ensure_open()
  File "/usr/lib/python3.6/site-packages/websockets/protocol.py", line 514, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```

It looks like the API is not responding with the expected output:

I ran this: 
```
#!/usr/bin/env python
import asyncio
import websockets
import json

async def test():
    async with websockets.connect('ws://localhost:5672') as websocket:
        payload = {
            "namespace": "connect",
            "method": "connect",
            "arguments": [
                "gpmdp-cli"
            ]
        }
        await websocket.send(json.dumps(payload))
        response = await websocket.recv()
        print(response)

asyncio.get_event_loop().run_until_complete(test())
```

According to [the documentation](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI_WebSocket.md#controlling-the-application) I should receive this response: `{
  "channel": "connect",
  "payload": "CODE_REQUIRED"
}`

But this is the response I get: `{"channel":"API_VERSION","payload":"1.1.0"}`

If I manually send a second payload with the 4 digit pin, I get no response, but the numbers do disappear from the player screen.

**Comment by Glitch-is** [comment]
@ConnorGriffin Are you sure you have enabled the API through the GPMDP settings correctly?

**Comment by ConnorGriffin** [comment]
Yes, and python is definitely interacting with it because the app pops up a 4 digit code when I run the script or the code snippet that I posted above. I'm going to do some more testing with different Python libraries or some other way to interact with websockets to find out what's going on. 

Edit: I ended up just using xdotool to simulate media key events for what I was going to be using this for. I messed with it in c# and had similar results, so I'm calling it quits.

**Comment by davewongillies** [comment]
I'm seeing this error too :'(

**Comment by freeSparrow** [comment]
@ConnorGriffin Dont know if you still need this but you can try to run the following code and see if you get {'channel': 'connect', 'payload': 'CODE_REQUIRED'} as output.

import asyncio
import websockets
import json

async def test():
    async with websockets.connect('ws://localhost:5672') as websocket:
        payload = {
            "namespace": "connect",
            "method": "connect",
            "arguments": ["gpmdp-cli"]
        }
        await websocket.send(json.dumps(payload))
        **while True:
            response = json.loads(await websocket.recv())**
            print(response)

asyncio.get_event_loop().run_until_complete(test())
